#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }


rating_score:
    path: /widget/{uuid}
    defaults: { _controller: 'App\Controller\HotelController::getRatingScoreAction'}